name: quizz
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  smooth_page_indicator: ^1.2.1
  nb_utils: ^7.1.3
  dots_indicator: ^4.0.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.4.0
  html: ^0.15.5
  intl: ^0.20.2
  path_provider_windows: ^2.3.0
  shared_preferences_windows: ^2.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/quizz/
    - images/quizz/quiz_logo.jpg
